name: background_json_parser
description: A flutter package of json parser.
version: 1.0.3
homepage: https://github.com/Mto292/json_parser.git

environment:
  sdk: ">=2.12.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:

  
  
  
  
  
  
  
  
  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
